name: Deploy Node Docker Image
on:
  push:
    branches:
      'developer'

permissions:
  contents: read
  packages: write

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to AWS Registry
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $AWS_REGISTRY_URL
        env:
          AWS_REGISTRY_URL: ${{ secrets.AWS_NODE_REGISTRY_URL }}

      - name: Build Node Image
        run: docker build -t oreowallet .

      - name: Deploy Node Image to AWS
        run: |
          docker tag oreowallet ${{ secrets.AWS_NODE_REGISTRY_URL }}/oreowallet:developer
          docker push ${{ secrets.AWS_NODE_REGISTRY_URL }}/oreowallet:developer
