on:
  pull_request:
  push:
    branches:
      - master

name: Rust CI

jobs:
  rust_lint:
    name: Lint Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          save-if: false
          shared-key: base

      - name: "`cargo fmt` check on ironfish-rust"
        run: |
          cargo fmt --all -- --check

      - name: "Clippy check on ironfish-rust"
        run: |
          cargo clippy --all-targets --all-features -- -D warnings
